name: CI (H2)

on:
  push:
    branches: [ "main" ]   # 필요 시 dev 추가
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - 'build.gradle'
              - 'settings.gradle'
              - 'gradlew'
              - 'gradlew.bat'
              - 'src/**'
            frontend:
              - 'frontend/**'

  backend:
    if: needs.changes.outputs.backend == 'true'
    needs: changes
    name: Backend (Gradle, H2)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Test (profile=test)
        env:
          SPRING_PROFILES_ACTIVE: test
        run: ./gradlew clean test --no-daemon

      - name: Build (skip tests)
        run: ./gradlew build -x test --no-daemon

      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: build/libs/*.jar
          if-no-files-found: error

  frontend:
    if: needs.changes.outputs.frontend == 'true'
    needs: changes
    name: Frontend (Vite)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 22.12.0
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist
          if-no-files-found: error
